/* Generated By:JJTree: Do not edit this line. ASTIncludeStatement.java */

package haui.app.jjshell;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class ASTIncludeStatement extends SimpleNode {
  
  String path;
  
  public ASTIncludeStatement(int id) {
    super(id);
  }

  public void interpret( Long id)
  {
    if( !ProcessStore.getInstance(id).checkPrecondition())
      return;

    try
    {
      // delete leading and ending <code>"</code>
      if( path.startsWith( "\""))
        path = path.substring( 1, path.length()-1);
      if( path != null)
      {
        parser = new JJShellParser( new FileInputStream( path));
      }
    }
    catch( FileNotFoundException e)
    {
      System.err.println( "Reduced Java Shell Interpreter Version 0.1: Include File " + path + " not found.");
      return;
    }
    try
    {
      parser.CompilationUnit();
      parser.jjtree.rootNode().interpret( id);
    }
    catch( ParseException e)
    {
      System.err.println( "Reduced Java Shell Interpreter Version 0.1:  Encountered errors during parse of include file " + path);
      e.printStackTrace();
    }
    catch( Exception e1)
    {
      System.err.println( "Reduced Java Shell Interpreter Version 0.1:  Encountered errors during interpretation/tree building for include file " + path);
      e1.printStackTrace();
    }
  }
}
