/* Generated By:JJTree&JavaCC: Do not edit this line. SplShellParserConstants.java */
package haui.app.splshell;

public interface SplShellParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int BOOL = 13;
  int BYTE = 14;
  int CHAR = 15;
  int DOUBLE = 16;
  int FLOAT = 17;
  int INT = 18;
  int LONG = 19;
  int SHORT = 20;
  int STRING = 21;
  int FILEREADER = 22;
  int FILEWRITER = 23;
  int VOID = 24;
  int CONTINUE = 25;
  int BREAK = 26;
  int CASE = 27;
  int DO = 28;
  int ELSE = 29;
  int FALSE = 30;
  int FOR = 31;
  int IF = 32;
  int IMPORT = 33;
  int READ = 34;
  int RETURN = 35;
  int SWITCH = 36;
  int TRUE = 37;
  int WHILE = 38;
  int WRITE = 39;
  int INTEGER_LITERAL = 40;
  int DECIMAL_LITERAL = 41;
  int HEX_LITERAL = 42;
  int OCTAL_LITERAL = 43;
  int FLOATING_POINT_LITERAL = 44;
  int EXPONENT = 45;
  int CHARACTER_LITERAL = 46;
  int STRING_LITERAL = 47;
  int IDENTIFIER = 91;
  int LETTER = 92;
  int DIGIT = 93;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"boolean\"",
    "\"byte\"",
    "\"char\"",
    "\"double\"",
    "\"float\"",
    "\"int\"",
    "\"long\"",
    "\"short\"",
    "\"string\"",
    "\"filereader\"",
    "\"filewriter\"",
    "\"void\"",
    "\"continue\"",
    "\"break\"",
    "\"case\"",
    "\"do\"",
    "\"else\"",
    "\"false\"",
    "\"for\"",
    "\"if\"",
    "\"import\"",
    "\"read\"",
    "\"return\"",
    "\"switch\"",
    "\"true\"",
    "\"while\"",
    "\"write\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"include\"",
    "\"(\"",
    "\"main\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"args\"",
    "\"{\"",
    "\"}\"",
    "\"++\"",
    "\"--\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"%=\"",
    "\"|=\"",
    "\"^=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\":\"",
    "\"default\"",
    "\"jsh\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
