/* Generated By:JJTree: Do not edit this line. R:\Dev\haui\components\javacc_test\src\java\SPLParserTreeConstants.java */

public interface SPLParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVARDECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTASSIGNMENT = 3;
  public int JJTORNODE = 4;
  public int JJTANDNODE = 5;
  public int JJTBITWISEORNODE = 6;
  public int JJTBITWISEXORNODE = 7;
  public int JJTBITWISEANDNODE = 8;
  public int JJTEQNODE = 9;
  public int JJTNENODE = 10;
  public int JJTLTNODE = 11;
  public int JJTGTNODE = 12;
  public int JJTLENODE = 13;
  public int JJTGENODE = 14;
  public int JJTADDNODE = 15;
  public int JJTSUBTRACTNODE = 16;
  public int JJTMULNODE = 17;
  public int JJTDIVNODE = 18;
  public int JJTMODNODE = 19;
  public int JJTBITWISECOMPLNODE = 20;
  public int JJTNOTNODE = 21;
  public int JJTID = 22;
  public int JJTINTCONSTNODE = 23;
  public int JJTTRUENODE = 24;
  public int JJTFALSENODE = 25;
  public int JJTBLOCK = 26;
  public int JJTSTATEMENTEXPRESSION = 27;
  public int JJTIFSTATEMENT = 28;
  public int JJTWHILESTATEMENT = 29;
  public int JJTREADSTATEMENT = 30;
  public int JJTWRITESTATEMENT = 31;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "VarDeclaration",
    "void",
    "Assignment",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "BitwiseComplNode",
    "NotNode",
    "Id",
    "IntConstNode",
    "TrueNode",
    "FalseNode",
    "Block",
    "StatementExpression",
    "IfStatement",
    "WhileStatement",
    "ReadStatement",
    "WriteStatement",
  };
}
