/* Generated By:JJTree&JavaCC: Do not edit this line. SPLParserConstants.java */
public interface SPLParserConstants {

  int EOF = 0;
  int INT = 6;
  int BOOL = 7;
  int INTEGER_LITERAL = 8;
  int IDENTIFIER = 41;
  int LETTER = 42;
  int DIGIT = 43;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"int\"",
    "\"boolean\"",
    "<INTEGER_LITERAL>",
    "\";\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"read\"",
    "\"write\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
